// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectNotify() {
  return window['go']['notify']['Notify']['ConnectNotify']();
}

export function DisconnectNotify() {
  return window['go']['notify']['Notify']['DisconnectNotify']();
}

export function SetContext(arg1) {
  return window['go']['notify']['Notify']['SetContext'](arg1);
}
