// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function DecodeData(arg1:{[key: string]: any}):Promise<entity.Message>;

export function DeleteData(arg1:{[key: string]: any},arg2:string):Promise<void>;

export function GetConfigsAndChangeCWD():Promise<Array<string>>;

export function GetData(arg1:string):Promise<Array<entity.Message>>;

export function IsWindows():Promise<boolean>;

export function Run():Promise<void>;

export function SaveData(arg1:{[key: string]: any},arg2:string):Promise<void>;

export function SaveToFrontendParams():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stoped():Promise<void>;
