// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecodeData(arg1) {
  return window['go']['gui']['Gui']['DecodeData'](arg1);
}

export function DeleteData(arg1, arg2) {
  return window['go']['gui']['Gui']['DeleteData'](arg1, arg2);
}

export function GetConfigsAndChangeCWD() {
  return window['go']['gui']['Gui']['GetConfigsAndChangeCWD']();
}

export function GetData(arg1) {
  return window['go']['gui']['Gui']['GetData'](arg1);
}

export function IsWindows() {
  return window['go']['gui']['Gui']['IsWindows']();
}

export function Run() {
  return window['go']['gui']['Gui']['Run']();
}

export function SaveData(arg1, arg2) {
  return window['go']['gui']['Gui']['SaveData'](arg1, arg2);
}

export function SaveToFrontendParams() {
  return window['go']['gui']['Gui']['SaveToFrontendParams']();
}

export function Startup(arg1) {
  return window['go']['gui']['Gui']['Startup'](arg1);
}

export function Stoped() {
  return window['go']['gui']['Gui']['Stoped']();
}
